version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      # Definimos as variáveis aqui e usamos IMEDIATAMENTE
      - REPO_BACKEND=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blog-backend
      - REPO_FRONTEND=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/blog-frontend
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

      # --- BACKEND ---
      - echo Building Backend...
      - cd backend
      - docker build -t $REPO_BACKEND:latest .
      - docker tag $REPO_BACKEND:latest $REPO_BACKEND:$IMAGE_TAG
      - echo Pushing Backend...
      - docker push $REPO_BACKEND:latest
      - docker push $REPO_BACKEND:$IMAGE_TAG
      - cd ..

      # --- FRONTEND ---
      - echo Building Frontend...
      - cd frontend
      - docker build -t $REPO_FRONTEND:latest .
      - docker tag $REPO_FRONTEND:latest $REPO_FRONTEND:$IMAGE_TAG
      - echo Pushing Frontend...
      - docker push $REPO_FRONTEND:latest
      - docker push $REPO_FRONTEND:$IMAGE_TAG
      
  post_build:
    commands:
      - echo Build and Push completed successfully.